### ISSUE TITLE
build error!!!

### ISSUE THREAD

**Issue by ahmedmoselhi** [carlo0815/openNFR-gui2#45]
ERROR: ExpansionError during parsing /home/openspabuilder/openspa/build-enviroment/meta-oe-alliance/meta-oe/recipes-oe-alliance/enigma2/enigma2.bb                               | ETA:  0:00:51
Traceback (most recent call last):
  File "/home/openspabuilder/openspa/build-enviroment/bitbake/lib/bb/fetch2/git.py", line 242, in Git.urldata_init(ud=<bb.fetch2.FetchData object at 0x7f008e6a1d68>, d=<bb.data_smart.DataSmart object at 0x7f008ec0cbe0>):

    >        ud.setup_revisions(d)

  File "/home/openspabuilder/openspa/build-enviroment/bitbake/lib/bb/fetch2/__init__.py", line 1305, in FetchData.setup_revisions(d=<bb.data_smart.DataSmart object at 0x7f008ec0cbe0>):
             for name in self.names:
    >            self.revisions[name] = srcrev_internal_helper(self, d, name)

  File "/home/openspabuilder/openspa/build-enviroment/bitbake/lib/bb/fetch2/__init__.py", line 1170, in srcrev_internal_helper(ud=<bb.fetch2.FetchData object at 0x7f008e6a1d68>, d=<bb.data_smart.DataSmart object at 0x7f008ec0cbe0>, name='default'):
         if srcrev == "AUTOINC":
    >        srcrev = ud.method.latest_revision(ud, d, name)

  File "/home/openspabuilder/openspa/build-enviroment/bitbake/lib/bb/fetch2/__init__.py", line 1565, in Git.latest_revision(ud=<bb.fetch2.FetchData object at 0x7f008e6a1d68>, d=<bb.data_smart.DataSmart object at 0x7f008ec0cbe0>, name='default'):
             except KeyError:
    >            revs[key] = rev = self._latest_revision(ud, d, name)
                 return rev
  File "/home/openspabuilder/openspa/build-enviroment/bitbake/lib/bb/fetch2/git.py", line 608, in Git._latest_revision(ud=<bb.fetch2.FetchData object at 0x7f008e6a1d68>, d=<bb.data_smart.DataSmart object at 0x7f008ec0cbe0>, name='default'):
             raise bb.fetch2.FetchError("Unable to resolve '%s' in upstream git repository in git ls-remote output for %s" % \
    >            (ud.unresolvedrev[name], ud.host+ud.path))

bb.data_smart.ExpansionError: Failure expanding variable SRCPV, expression was ${@bb.fetch2.get_srcrev(d)} which triggered exception FetchError: Fetcher failure: Unable to resolve 'nextp3' in upstream git repository in git ls-remote output for github.com/carlo0815/openNFR-gui2.git

**Comment by carlo0815** [comment]
it's normal, you want to try build a Branch but this Branch not exist.
and why you want our Enigma2 for openspa?

**Comment by ahmedmoselhi** [comment]
> it's normal, you want to try build a Branch but this Branch not exist.
> and why you want our Enigma2 for openspa?

it's name for user and folder but i want to build opennfr latest for spark amiko8900
can i do that???

**Comment by carlo0815** [comment]
yes you can but not with nextp3 this branch doesn't exist look in Git witch Branch you want

**Comment by carlo0815** [comment]
but Spark is sh4 and i don't know if our lastest Enigma2 works with it, we stop sh4 some years ago

**Comment by ahmedmoselhi** [comment]
> yes you can but not with nextp3 this branch doesn't exist look in Git witch Branch you want
i just cloned oe allience 4.3 branch and tried to build but got this error

**Comment by carlo0815** [comment]
then learn to change build branch and try again we don*t support sh4 builds
